### PR TITLE
Feature/tc 128  basicpage styling

### PR DESCRIPTION
**Pull request by ivanbueno-jcc**

### CODE REVIEW

**Comment by sleepingmonk** [comment]
I would not merge this to master.

1. There is an inline style tag.  That should be in SCSS somewhere.
2. What are the field templates for, other than adding a class?  There are other ways to add classes or styling that doesn't require another template.  I would try to keep the number of custom templates to a minimum.  Use only when required to structure the markup differently.  And field level templates are usually pretty minimalistic, without much to restructure.
3. There are several "FIXME" comments.  It may be personal preference but "@todo" is what I've seen and use for these types of comments as a string to search for.  However, can we not fix these issues before committing this code to master?  We should be thinking of master as Production, as much as possible.  Things go in there when they're "done".  

Would it be helpful to discuss solutions to the requirements of this feature?  Maybe we can find a cleaner approach and refine some guidelines for the general approach to theming things like this.

**Comment by melwong-jcc** [comment]
Field templates are to override the default Drupal markup to use proper formatting especially if we want to avoid duplicating customized markup between content types. For example, Nelson now won't need to worry about styling or formatting Division, Subject Matter, Related Links, and Tags when he utilizes those field content variables.

In general, we cannot wait on courtyard components and updates unless we delay TC development hence some of the undesirable placeholder code and FIXME (soon to be TODO) notations. It's the reality with our timeline which unfortunately goes against ideal practices. In fact, we won't know what is missing from courtyard unless we start coding for TC.

I am open to suggestion on how we can create TC progress while minimizing the amount of rework as much as possible for components since we know that courtyard must provide everything for TC.

**Comment by ivanbueno-jcc** [comment]
@melwong-jcc
1. For fields that need extra classes (margin-bottom-2, text-bold), template is not needed.  Here are some options:

 a. Add via the theme preprocess hooks. For example, https://github.com/JudicialCouncilOfCalifornia/trialcourt/blob/develop/web/themes/custom/jcc_base/includes/field.inc

 b. Use modules:
   * https://www.drupal.org/project/field_formatter_class
   * https://www.drupal.org/project/element_class_formatter

@sleepingmonk 
a. What do you think about the class formatter modules above?  Worth it?
b. It might be useful to create a /preprocess folder (similar to /templates) in the theme for organization and convenience.

**Comment by melwong-jcc** [comment]
No modules necessary and will look into using SASS to solve most of the inline CSS concerns and potentially to build the simple comma delimited listings

**Comment by melwong-jcc** [comment]
Closing master PR to revisit implementation

**Pull request closed without merging**
