### PR TITLE
Feature/tc 173  readmorelinkcolor fix

### PR DESCRIPTION
**Pull request by melwong-jcc**

### CODE REVIEW

**Comment by melwong-jcc** [comment]
Another FYI CSS bug fix to remove conflict with courtyward

**Comment by ivanbueno-jcc** [comment]
looks good to me

**Comment by ivanbueno-jcc** [comment]
> Another FYI CSS bug fix to remove conflict with courtyward

We'll need to revisit courtyard again later.  If it's truly themable, we wouldn't need to do this overrides.

**Comment by melwong-jcc** [comment]
Seems that the button CSS specifically visited state depends too much on other factors. For example, for document type, in order to ensure the text is colored white in any link state, you need wrap the link with a DIV. Who is going to know that?

**Pull request merged**
